title: Uday Gatti
description: Data Analyst | Analytics & Systems Professional
email: gattiuday@gmail.com
location: Phoenix, AZ
linkedin_url: https://in.linkedin.com/in/gattiuday

# Navigation
header_pages:
  - about.md
  - skills.md
  - experience.md
  - projects.md
  - education.md
